default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  prepared_statements: false

development:
  <<: *default
  database: devboard_development
  username: mariotmc
  password:
  host: localhost

test:
  <<: *default
  database: devboard_test
  username: mariotmc
  password:
  host: localhost

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  database: devboard_production
  # username: devboard
  # password: <%= ENV["DEVBOARD_DATABASE_PASSWORD"] %>
  prepared_statements: false
